FROM rust:1.82-bookworm

RUN apt update && apt upgrade -y && apt install -y git curl
COPY . /app
WORKDIR /app
RUN cargo install --path .

ENTRYPOINT particl-blockchain-parser --rpc-ip particld:51735 --rpc-user user --rpc-password password --stage example --surrealdb-ip surrealdb:8000
